name: lamps_incubation
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base>=4.2.2
  - r-tidyverse>=1.3.2
  - r-renv>=v0.16.0
  - wget=1.20.3
  - snakemake=7.18.2
  - graphviz=6.0.1
  - coreutils>=9.1
